# to create a conda environment, run $ conda env create -f environment.yml
name: rxnrep
channels:
  - pytorch
  - dglteam
  - conda-forge
  - defaults
dependencies:
  - requests
  - numpy
  - pandas
  - rich
  - pyyaml
  - scikit-learn
  - python==3.9.2
  - pytorch==1.8.0
  - pytorch-lightning==1.3.2
  - dgl==0.6.0
  - pymatgen==2020.8.13
  - rdkit==2020.03.5
  - openbabel==3.1.1